In [1]:
import numpy as np


print("=" * 40)

print("    FITNESS STEP COUNTER")

print("=" * 40)


# Daily step count for 7 days

steps = np.array([6500, 7200, 8100, 9000, 7800, 10500, 9500])


print("\nDaily Steps:")

print(steps)


# Change in steps between days

step_change = np.diff(steps)


print("\nDaily Change in Steps:")

print(step_change)


# Total steps

total_steps = np.sum(steps)


print("\nTotal Weekly Steps:")

print(total_steps)


# Average steps

avg_steps = np.mean(steps)


print("\nAverage Daily Steps:")

print(round(avg_steps, 2))


# Maximum steps

max_steps = np.max(steps)


print("\nMaximum Steps:")

print(max_steps)


# Minimum steps

min_steps = np.min(steps)


print("\nMinimum Steps:")

print(min_steps)


# Day with highest steps

max_day = np.argmax(steps)


print("\nHighest Step Count:")

print(f"Day {max_day + 1}: {steps[max_day]} steps")


# Day with lowest steps

min_day = np.argmin(steps)


print("\nLowest Step Count:")

print(f"Day {min_day + 1}: {steps[min_day]} steps")


# Cumulative steps

cumulative_steps = np.cumsum(steps)


print("\nCumulative Steps:")

print(cumulative_steps)


# Percentage contribution

percentage_steps = (steps / total_steps) * 100


print("\nPercentage Contribution:")

print(np.round(percentage_steps, 2))


# Total movement variation

total_variation = np.sum(np.abs(step_change))


print("\nTotal Step Variation:")

print(total_variation)


# Median

median_steps = np.median(steps)


print("\nMedian Steps:")

print(median_steps)


# Standard deviation

std_steps = np.std(steps)


print("\nStandard Deviation:")

print(round(std_steps, 2))


# Range

step_range = np.ptp(steps)


print("\nStep Range:")

print(step_range)


# Goal achievement (8000 steps)

goal_steps = steps[steps >= 8000]


print("\nDays Achieving 8000+ Steps:")

print(goal_steps)


# Calories burned (Approx 0.04 calories per step)

calories = steps * 0.04


print("\nCalories Burned Per Day:")

print(np.round(calories, 2))


# Total calories burned

total_calories = np.sum(calories)


print("\nTotal Calories Burned:")

print(round(total_calories, 2))


print("\n" + "=" * 40)

print("         FITNESS SUMMARY")

print("=" * 40)

print("Total Steps        :", total_steps)

print("Average Steps      :", round(avg_steps, 2))

print("Maximum Steps      :", max_steps)

print("Minimum Steps      :", min_steps)

print("Total Calories     :", round(total_calories, 2))

print("Fitness Goal       :", "Achieved")

print("=" * 40)

print("Fitness Tracking Completed.")

    FITNESS STEP COUNTER

Daily Steps:
[ 6500  7200  8100  9000  7800 10500  9500]

Daily Change in Steps:
[  700   900   900 -1200  2700 -1000]

Total Weekly Steps:
58600

Average Daily Steps:
8371.43

Maximum Steps:
10500

Minimum Steps:
6500

Highest Step Count:
Day 6: 10500 steps

Lowest Step Count:
Day 1: 6500 steps

Cumulative Steps:
[ 6500 13700 21800 30800 38600 49100 58600]

Percentage Contribution:
[11.09 12.29 13.82 15.36 13.31 17.92 16.21]

Total Step Variation:
7400

Median Steps:
8100.0

Standard Deviation:
1280.31

Step Range:
4000

Days Achieving 8000+ Steps:
[ 8100  9000 10500  9500]

Calories Burned Per Day:
[260. 288. 324. 360. 312. 420. 380.]

Total Calories Burned:
2344.0

         FITNESS SUMMARY
Total Steps        : 58600
Average Steps      : 8371.43
Maximum Steps      : 10500
Minimum Steps      : 6500
Total Calories     : 2344.0
Fitness Goal       : Achieved
Fitness Tracking Completed.
